### PR TITLE
feat: add a prop to enable/disable page scroll

### PR DESCRIPTION
**Pull request by therealpecus**
Disabling scrolling on the underlying page makes sense and Vue Cool Lightbox takes care of fixing the body while preserving the page position. In some situations this might be undesirable (such as in case of conflicts on inline styles on the body element or when a component or animation framework overrides page positioning).

In these case, a new prop `enableScrollLock` (which defaults to `true` to guarantee backward compatibility) provides a way,  when set to `false`, to avoid Vue Cool Lightbox setting CSS styles on the body element that prevent page scroll.

### CODE REVIEW

**Comment by lucaspulliese** [comment]
You are the best, thanks for the PR, I will update it to npm and notify you

**Comment by lucaspulliese** [comment]
Hi @therealpecus, I updated the component with your changes and in the version 2.5.2 you can use the prop enableScrollLock.  

So thanks you again and I'm going to add you to the [acknowledgements section](https://vue-cool-lightbox.lucaspulliese.com/#acknowledgements).

**Comment by therealpecus** [comment]
Thank you @lucaspulliese ! I had missed your feedback, kudos again for a very well crafted component!

**Comment by lucaspulliese** [comment]
No problem, thank you very much for the PR!

**Pull request merged**
